title: Ryans Rants, and rambling
author: Ryan B
email: ryanbjork1@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'll be documenting all my code i've learned. And other things.

# social links
twitter_username: ryanbjork1 # DO NOT include the @ character, or else the build will fail!
github_username:  ryanb1-hub # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
